import { Category, Product } from "./supabase";

export const demoCategories: Category[] = [
  {
    id: "1",
    name: "Corrugated Boxes",
    slug: "corrugated-boxes",
    description: "High-quality corrugated packaging boxes",
    icon_emoji: "📦",
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Plastic Containers",
    slug: "plastic-containers",
    description: "Durable plastic containers for food and storage",
    icon_emoji: "🥤",
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Paper Bags",
    slug: "paper-bags",
    description: "Eco-friendly paper bags for retail and food",
    icon_emoji: "🛍️",
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Foam Packaging",
    slug: "foam-packaging",
    description: "Protective foam packaging materials",
    icon_emoji: "🧊",
    display_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Bubble Wrap",
    slug: "bubble-wrap",
    description: "Protective bubble wrap for fragile items",
    icon_emoji: "🫧",
    display_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Tape & Adhesives",
    slug: "tape-adhesives",
    description: "Packaging tapes and adhesive solutions",
    icon_emoji: "📌",
    display_order: 6,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const demoProducts: Product[] = [
  {
    id: "p1",
    name: "5 Ply Corrugated Box - 12x10x8",
    category_id: "1",
    description:
      "Premium 5-ply corrugated boxes with excellent strength and durability",
    price: 45,
    unit_of_measure: "Box",
    quantity_in_unit: 100,
    sku: "CCB-5PLY-12108",
    image_url:
      "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=500&fit=crop",
    image_alt_text: "Premium corrugated box",
    is_active: true,
    is_featured: true,
    display_order: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p2",
    name: "Clear Plastic Container - 500ml",
    category_id: "2",
    description: "Food-grade clear plastic containers with secure lids",
    price: 12,
    unit_of_measure: "Piece",
    quantity_in_unit: 500,
    sku: "PC-CLR-500ML",
    image_url:
      "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=500&fit=crop",
    image_alt_text: "Clear plastic container",
    is_active: true,
    is_featured: true,
    display_order: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p3",
    name: "Kraft Paper Bag - Medium",
    category_id: "3",
    description:
      "Eco-friendly kraft paper bags, perfect for retail and food packaging",
    price: 8,
    unit_of_measure: "Piece",
    quantity_in_unit: 1000,
    sku: "PB-KRAFT-MED",
    image_url:
      "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500&h=500&fit=crop",
    image_alt_text: "Kraft paper bag",
    is_active: true,
    is_featured: true,
    display_order: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p4",
    name: "Foam Sheet - 1 inch thickness",
    category_id: "4",
    description: "Protective foam sheets for cushioning and insulation",
    price: 25,
    unit_of_measure: "Sheet",
    quantity_in_unit: 50,
    sku: "FS-FOAM-1IN",
    image_url:
      "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=500&fit=crop",
    image_alt_text: "Foam sheet",
    is_active: true,
    is_featured: false,
    display_order: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p5",
    name: "Bubble Wrap Roll - 12 inch width",
    category_id: "5",
    description:
      "Protective bubble wrap with air-filled bubbles for maximum protection",
    price: 35,
    unit_of_measure: "Roll",
    quantity_in_unit: 100,
    sku: "BW-ROLL-12IN",
    image_url:
      "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=500&fit=crop",
    image_alt_text: "Bubble wrap roll",
    is_active: true,
    is_featured: false,
    display_order: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "p6",
    name: "Brown Packing Tape - 2 inch",
    category_id: "6",
    description: "Strong adhesive brown packing tape for secure sealing",
    price: 5,
    unit_of_measure: "Roll",
    quantity_in_unit: 36,
    sku: "PT-BROWN-2IN",
    image_url:
      "https://images.unsplash.com/photo-1578500494198-246f612d03b3?w=500&h=500&fit=crop",
    image_alt_text: "Packing tape",
    is_active: true,
    is_featured: false,
    display_order: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
